"""
Resource Quiz API
─────────────────
After a user finishes viewing a learning resource they are shown 2 MCQ
questions generated by OpenAI GPT that are PERSONALISED per user:

  Question generation uses:
    1. Resource title, topic, subtopic, description
    2. User's current level  (beginner / intermediate / advanced)
    3. User's known misconceptions  (concept_tag + how many times seen)
    4. Topics the user has already studied  (from quiz attempt history)

  The questions are NOT cached — every user gets a fresh set tailored
  to their own misconceptions so we can track whether those misconceptions
  improve over time.

Submitting answers:
  • Records each answer in user_resource_quiz_attempts
  • Updates UserMisconception for wrong answers (count++)
  • For correct answers on a previously-wrong concept, count is NOT
    decremented here — improvement is inferred by the caller comparing
    counts over time.
  • Generates an LLM explanation for each wrong answer
  • Marks the resource as viewed (upserts UserLearningResource)
  • Re-evaluates the user's level based on rolling quiz performance

Level update logic
──────────────────
We look at the user's last 20 resource-quiz answers.
  ≥ 80 % correct  → promote  (beginner → intermediate → advanced)
  ≤ 40 % correct  → demote   (advanced → intermediate → beginner)
  otherwise        → keep current level
"""
from __future__ import annotations

import os
import json
import httpx
from datetime import datetime, timezone
from typing import List, Optional
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session
from sqlalchemy import func

from app.dependencies import get_db, get_current_user_id
from app.models.user import User
from app.models.learning_resource import LearningResource
from app.models.resource_quiz import ResourceQuizQuestion, UserResourceQuizAttempt
from app.models.user_learning_resource import UserLearningResource
from app.models.user_misconception import UserMisconception

router = APIRouter()

# ── level ordering ─────────────────────────────────────────────────────────────
LEVEL_ORDER = ["beginner", "intermediate", "advanced"]

PROMOTE_THRESHOLD = 0.80
DEMOTE_THRESHOLD  = 0.40
ROLLING_WINDOW    = 20


# ══════════════════════════════════════════════════════════════════════════════
# Pydantic schemas
# ══════════════════════════════════════════════════════════════════════════════

class QuizAnswerIn(BaseModel):
    question_id: int
    chosen_option: str          # 'a','b','c','d'


class SubmitQuizRequest(BaseModel):
    user_id: UUID
    resource_id: int
    answers: List[QuizAnswerIn]


# ══════════════════════════════════════════════════════════════════════════════
# LLM helpers  (OpenAI GPT-4o-mini)
# ══════════════════════════════════════════════════════════════════════════════

def _call_openai(prompt: str, max_tokens: int = 800) -> str:
    """
    Raw call to OpenAI chat completions endpoint.
    Reads OPENAI_API_KEY from environment.  Raises on any error.
    """
    api_key = os.environ.get("OPENAI_API_KEY", "")
    if not api_key:
        raise ValueError("OPENAI_API_KEY is not set in environment")

    response = httpx.post(
        "https://api.openai.com/v1/chat/completions",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "model": "gpt-4o-mini",          # fast + cheap; swap to gpt-4o if needed
            "max_tokens": max_tokens,
            "temperature": 0.4,              # low temp = consistent, focused output
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "You are an expert digital logic professor. "
                        "You create precise, pedagogically sound multiple-choice questions. "
                        "You always respond with valid JSON only — no markdown, no prose."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
        },
        timeout=25.0,
    )
    response.raise_for_status()
    data = response.json()
    return data["choices"][0]["message"]["content"].strip()


def _build_question_prompt(
    resource: "LearningResource",
    user_level: str,
    misconceptions: list[dict],   # [{"concept_tag": str, "count": int, "last_seen": str}, ...]
    studied_topics: list[str],    # topics the user already completed quizzes on
) -> str:
    """
    Build the personalised question-generation prompt from all available
    user context.  This is the core of the personalisation system.
    """
    topic    = (resource.topic    or "digital logic").replace("_", " ")
    subtopic = (resource.subtopic or "").replace("_", " ")
    title    = resource.title or topic
    desc     = (resource.description or "")[:600] or "No description provided."

    # ── Level guidance ──────────────────────────────────────────────────────
    level_guidance = {
        "beginner": (
            "The student is a BEGINNER. Use simple vocabulary. "
            "Questions should test basic conceptual understanding — "
            "definitions, simple truth tables, direct application. "
            "Avoid tricky edge cases."
        ),
        "intermediate": (
            "The student is at INTERMEDIATE level. "
            "Questions should require applying concepts to small examples, "
            "comparing alternatives, or identifying correct circuit behaviour."
        ),
        "advanced": (
            "The student is ADVANCED. "
            "Questions should require deep reasoning — multi-step problems, "
            "subtle distinctions, optimisation trade-offs, or edge cases."
        ),
    }.get(user_level.lower(), "The student's level is unknown; aim for intermediate difficulty.")

    # ── Misconception section ───────────────────────────────────────────────
    if misconceptions:
        misc_lines = []
        for m in misconceptions[:4]:          # top 4 most frequent
            tag   = m["concept_tag"].replace("_", " ")
            count = m["count"]
            misc_lines.append(f'  • "{tag}" — wrong {count} time(s)')
        misc_block = (
            "KNOWN MISCONCEPTIONS (most important — at least one question MUST "
            "directly probe whether this misconception persists or has been corrected):\n"
            + "\n".join(misc_lines)
            + "\n\nFor each misconception question: make the wrong answer reflect exactly "
            "how a student with THAT misconception would reason, so a correct answer "
            "proves the misconception is resolved."
        )
    else:
        misc_block = (
            "No known misconceptions yet. Generate two well-rounded questions "
            "that cover the most important concepts of this resource."
        )

    # ── Prior study context ─────────────────────────────────────────────────
    if studied_topics:
        prior = ", ".join(t.replace("_", " ") for t in studied_topics[:6])
        prior_block = f"Topics already studied by this student: {prior}."
    else:
        prior_block = "This is one of the student's first resources."

    # ── Final prompt ────────────────────────────────────────────────────────
    return f"""You are creating a personalised 2-question quiz for a digital logic student.

=== LEARNING RESOURCE ===
Title:       {title}
Topic:       {topic}{(' / ' + subtopic) if subtopic else ''}
Description: {desc}

=== STUDENT PROFILE ===
Level:  {user_level.capitalize()}
Instruction: {level_guidance}
{prior_block}

=== MISCONCEPTION TARGETING ===
{misc_block}

=== YOUR TASK ===
Generate exactly 2 multiple-choice questions.
Rules:
- Each question has exactly 4 options (a, b, c, d) with ONE correct answer.
- Wrong options must be plausible — common mistakes, not obviously silly.
- The concept_tag field must be a short snake_case label for the concept tested
  (e.g. "boolean_algebra", "karnaugh_map", "flip_flop_timing").
- Questions must be directly answerable from the resource described above.
- Difficulty must match the student level described.

Respond ONLY with a valid JSON array — no markdown fences, no explanation:
[
  {{
    "question_text": "...",
    "option_a": "...",
    "option_b": "...",
    "option_c": "...",
    "option_d": "...",
    "correct_option": "a",
    "concept_tag": "snake_case_concept"
  }},
  {{
    "question_text": "...",
    "option_a": "...",
    "option_b": "...",
    "option_c": "...",
    "option_d": "...",
    "correct_option": "b",
    "concept_tag": "snake_case_concept"
  }}
]"""


def _llm_generate_questions(
    resource: "LearningResource",
    user_level: str,
    misconceptions: list[dict],
    studied_topics: list[str],
) -> list[dict]:
    """
    Call OpenAI to generate 2 personalised MCQ questions.
    Falls back to static questions on any failure.

    Args:
        resource:        The LearningResource ORM object.
        user_level:      'beginner' | 'intermediate' | 'advanced'
        misconceptions:  List of dicts from UserMisconception rows.
        studied_topics:  List of topic strings the user already attempted.
    """
    prompt = _build_question_prompt(resource, user_level, misconceptions, studied_topics)
    try:
        raw = _call_openai(prompt, max_tokens=1000)

        # Strip accidental markdown fences
        raw = raw.strip()
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        raw = raw.strip()

        questions = json.loads(raw)

        required = {
            "question_text", "option_a", "option_b",
            "option_c", "option_d", "correct_option",
        }
        for q in questions:
            assert required.issubset(q.keys()), f"Missing keys in question: {q.keys()}"
            assert q["correct_option"] in ("a", "b", "c", "d"), \
                f"Invalid correct_option: {q['correct_option']}"

        print(f"[quiz] Generated {len(questions)} personalised questions via OpenAI "
              f"for resource {resource.id}, user_level={user_level}, "
              f"misconceptions={[m['concept_tag'] for m in misconceptions[:4]]}")
        return questions[:2]

    except Exception as e:
        print(f"[quiz] OpenAI question generation failed: {e!r} — using static fallback")
        return _static_fallback_questions(resource)


def _static_fallback_questions(resource: "LearningResource") -> list[dict]:
    """Hardcoded fallback when OpenAI is unavailable."""
    topic = (resource.topic or "this topic").replace("_", " ")
    return [
        {
            "question_text": f"Which of the following best describes a key concept in {topic}?",
            "option_a": "It simplifies complex logic into basic operations",
            "option_b": "It always increases system complexity",
            "option_c": "It is only applicable to analog circuits",
            "option_d": "It removes the need for binary representation",
            "correct_option": "a",
            "concept_tag": resource.topic or "general",
        },
        {
            "question_text": f"What is the primary purpose of studying {topic}?",
            "option_a": "To memorise all possible truth tables",
            "option_b": "To design and analyse digital logic systems",
            "option_c": "To replace software with hardware unconditionally",
            "option_d": "To avoid using Boolean algebra",
            "correct_option": "b",
            "concept_tag": resource.topic or "general",
        },
    ]


def _ai_explain_wrong_answer(
    question_text: str,
    chosen_option: str,
    chosen_text: str,
    correct_option: str,
    correct_text: str,
    concept_tag: str | None,
) -> str:
    """
    Ask OpenAI to produce a short, encouraging explanation of why the
    student's answer was wrong.  Falls back to a plain string.
    """
    topic_label = concept_tag.replace("_", " ") if concept_tag else "digital logic"
    prompt = (
        f"A student answered a digital logic quiz question incorrectly.\n\n"
        f"Question: {question_text}\n"
        f"Student chose ({chosen_option.upper()}): {chosen_text}\n"
        f"Correct answer ({correct_option.upper()}): {correct_text}\n"
        f"Topic: {topic_label}\n\n"
        "In 2-3 concise sentences, explain encouragingly WHY the student's choice "
        "is incorrect and what makes the correct answer right. "
        "Keep language simple and supportive. Do not use bullet points."
    )
    try:
        return _call_openai(prompt, max_tokens=200)
    except Exception:
        return (
            f"The correct answer is {correct_option.upper()}: \"{correct_text}\". "
            f"Review the material on {topic_label} to strengthen this concept."
        )


# ══════════════════════════════════════════════════════════════════════════════
# DB helpers
# ══════════════════════════════════════════════════════════════════════════════

def _record_misconception(db: Session, user_id: UUID, concept_tag: str) -> None:
    existing = db.query(UserMisconception).filter(
        UserMisconception.user_id == user_id,
        UserMisconception.concept_tag == concept_tag,
    ).first()
    if existing:
        existing.count += 1
        existing.last_seen = datetime.utcnow()
    else:
        db.add(UserMisconception(
            user_id=user_id,
            concept_tag=concept_tag,
            count=1,
            first_seen=datetime.utcnow(),
            last_seen=datetime.utcnow(),
        ))


def _update_level(db: Session, user: User) -> str:
    recent = (
        db.query(UserResourceQuizAttempt.is_correct)
        .filter(UserResourceQuizAttempt.user_id == user.id)
        .order_by(UserResourceQuizAttempt.answered_at.desc())
        .limit(ROLLING_WINDOW)
        .all()
    )
    if not recent:
        return user.level or "beginner"

    correct = sum(1 for (r,) in recent if r)
    ratio = correct / len(recent)

    current = (user.level or "beginner").lower()
    idx = LEVEL_ORDER.index(current) if current in LEVEL_ORDER else 0

    if ratio >= PROMOTE_THRESHOLD and idx < len(LEVEL_ORDER) - 1:
        new_level = LEVEL_ORDER[idx + 1]
    elif ratio <= DEMOTE_THRESHOLD and idx > 0:
        new_level = LEVEL_ORDER[idx - 1]
    else:
        new_level = current

    if new_level != current:
        user.level = new_level
        db.commit()

    return new_level


# ══════════════════════════════════════════════════════════════════════════════
# Routes
# ══════════════════════════════════════════════════════════════════════════════

@router.get("/questions/{resource_id}")
def get_quiz_questions(
    resource_id: int,
    user_id: Optional[UUID] = None,
    db: Session = Depends(get_db),
    current_user_id: str = Depends(get_current_user_id),
):
    """
    Return 2 personalised quiz questions for the given resource.

    Questions are generated FRESH per user every call, personalised using:
      • The user's current level  (beginner / intermediate / advanced)
      • Their known misconceptions (concept_tag + how many times wrong)
      • Topics they have already studied (from past quiz attempt history)

    Generated questions are persisted so submit can look them up by ID.
    """
    resource = db.query(LearningResource).filter(LearningResource.id == resource_id).first()
    if not resource:
        raise HTTPException(status_code=404, detail="Resource not found")

    # ── Collect user context for personalisation ─────────────────────────────
    user_level     = "beginner"
    misconceptions = []    # [{"concept_tag": str, "count": int, "last_seen": str}]
    studied_topics = []    # distinct topic strings from past quiz attempts

    if user_id:
        user = db.query(User).filter(User.id == user_id).first()
        if user:
            user_level = (user.level or "beginner").lower()

        # Misconceptions: most frequent first (top 5)
        misc_rows = (
            db.query(UserMisconception)
            .filter(UserMisconception.user_id == user_id)
            .order_by(UserMisconception.count.desc())
            .limit(5)
            .all()
        )
        misconceptions = [
            {
                "concept_tag": m.concept_tag,
                "count":       m.count,
                "last_seen":   m.last_seen.strftime("%Y-%m-%d") if m.last_seen else "",
            }
            for m in misc_rows
        ]

        # Topics already studied = topics of resources the user attempted before
        past_ids = (
            db.query(UserResourceQuizAttempt.learning_resource_id)
            .filter(UserResourceQuizAttempt.user_id == user_id)
            .distinct()
            .all()
        )
        if past_ids:
            topic_rows = (
                db.query(LearningResource.topic)
                .filter(LearningResource.id.in_([r[0] for r in past_ids]))
                .distinct()
                .all()
            )
            studied_topics = [t[0] for t in topic_rows if t[0]]

    # ── Generate personalised questions via OpenAI ───────────────────────────
    raw = _llm_generate_questions(resource, user_level, misconceptions, studied_topics)

    new_qs = []
    for r in raw:
        q = ResourceQuizQuestion(
            learning_resource_id=resource_id,
            question_text=r["question_text"],
            option_a=r["option_a"],
            option_b=r["option_b"],
            option_c=r["option_c"],
            option_d=r["option_d"],
            correct_option=r["correct_option"],
            concept_tag=r.get("concept_tag"),
        )
        db.add(q)
        new_qs.append(q)

    db.commit()
    for q in new_qs:
        db.refresh(q)

    return {
        "resource_id": resource_id,
        "user_level":  user_level,
        "questions": [
            {
                "id": q.id,
                "question_text": q.question_text,
                "options": {
                    "a": q.option_a,
                    "b": q.option_b,
                    "c": q.option_c,
                    "d": q.option_d,
                },
                "concept_tag": q.concept_tag,
            }
            for q in new_qs
        ],
    }


@router.post("/submit")
def submit_quiz(
    body: SubmitQuizRequest,
    db: Session = Depends(get_db),
    current_user_id: str = Depends(get_current_user_id),
):
    """
    Record quiz answers, update misconceptions + level, mark resource viewed.
    Returns score + new level + which answers were right/wrong + LLM explanations.
    """
    user = db.query(User).filter(User.id == body.user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    resource = db.query(LearningResource).filter(LearningResource.id == body.resource_id).first()
    if not resource:
        raise HTTPException(status_code=404, detail="Resource not found")

    results = []
    score = 0

    for ans in body.answers:
        question = db.query(ResourceQuizQuestion).filter(
            ResourceQuizQuestion.id == ans.question_id,
            ResourceQuizQuestion.learning_resource_id == body.resource_id,
        ).first()

        if not question:
            continue

        chosen = (ans.chosen_option or "").lower().strip()
        is_correct = chosen == question.correct_option.lower()

        option_map = {
            "a": question.option_a,
            "b": question.option_b,
            "c": question.option_c,
            "d": question.option_d,
        }

        if is_correct:
            score += 1
            explanation = None
        else:
            if question.concept_tag:
                _record_misconception(db, user.id, question.concept_tag)
            explanation = _ai_explain_wrong_answer(
                question_text=question.question_text,
                chosen_option=chosen,
                chosen_text=option_map.get(chosen, ""),
                correct_option=question.correct_option,
                correct_text=option_map.get(question.correct_option.lower(), ""),
                concept_tag=question.concept_tag,
            )

        db.add(UserResourceQuizAttempt(
            user_id=user.id,
            learning_resource_id=body.resource_id,
            question_id=question.id,
            chosen_option=chosen,
            is_correct=is_correct,
            answered_at=datetime.utcnow(),
        ))

        results.append({
            "question_id": question.id,
            "chosen": chosen,
            "correct": question.correct_option,
            "is_correct": is_correct,
            "explanation": explanation,
        })

    # Mark resource as viewed (if not already)
    already = db.query(UserLearningResource).filter(
        UserLearningResource.user_id == user.id,
        UserLearningResource.learning_resource_id == body.resource_id,
    ).first()
    if not already:
        db.add(UserLearningResource(
            user_id=user.id,
            learning_resource_id=body.resource_id,
        ))

    user.last_active_at = datetime.now(tz=timezone.utc)
    db.commit()

    new_level = _update_level(db, user)

    misconceptions = (
        db.query(UserMisconception)
        .filter(UserMisconception.user_id == user.id)
        .order_by(UserMisconception.count.desc())
        .limit(5)
        .all()
    )

    return {
        "score": score,
        "total": len(results),
        "percentage": round((score / len(results)) * 100) if results else 0,
        "results": results,
        "new_level": new_level,
        "level_changed": new_level != (user.level or "beginner"),
        "top_misconceptions": [
            {"concept_tag": m.concept_tag, "count": m.count}
            for m in misconceptions
        ],
    }


@router.get("/history/{user_id}/{resource_id}")
def get_quiz_history(
    user_id: UUID,
    resource_id: int,
    db: Session = Depends(get_db),
    current_user_id: str = Depends(get_current_user_id),
):
    """Returns whether the user has already attempted the quiz for a resource."""
    attempts = (
        db.query(UserResourceQuizAttempt)
        .filter(
            UserResourceQuizAttempt.user_id == user_id,
            UserResourceQuizAttempt.learning_resource_id == resource_id,
        )
        .all()
    )
    return {
        "attempted": len(attempts) > 0,
        "score": sum(1 for a in attempts if a.is_correct),
        "total": len(attempts),
    }